# Generated by Django 4.1.3 on 2022-12-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': 'Biodata'},
        ),
    ]
