# Generated by Django 4.1.3 on 2022-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_berita_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='berita',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='berita',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
